frappe.query_reports["Egresos por Concepto"] = {
	filters: [
		{
			fieldname: "from_date",
			label: __("Desde"),
			fieldtype: "Date",
			default: frappe.datetime.month_start(),
			reqd: 1,
		},
		{
			fieldname: "to_date",
			label: __("Hasta"),
			fieldtype: "Date",
			default: frappe.datetime.get_today(),
			reqd: 1,
		},
		{
			fieldname: "local",
			label: __("Local"),
			fieldtype: "Select",
			options: ["", "CENTRAL", "GRAND BOURG", "JOSE C. PAZ", "SAN MIGUEL", "PILAR", "DEPÓSITO"].join("\n"),
		},
		{
			fieldname: "concepto",
			label: __("Concepto"),
			fieldtype: "Select",
			options: [
				"",
				"Gastos Generales",
				"Sueldos",
				"Aportes Obra Social",
				"Pagos ARCA",
				"Cuotas de ARCA",
				"Cuotas de ARBA",
				"Cuotas de Municipio",
				"Patentes de Autos",
				"Pagos Alquileres",
				"Pagos Cheques Bco",
				"Gastos Bancarios",
				"Pago Cuotas Préstamos Bco",
				"Retiros",
				"Imp. Provincial",
			].join("\n"),
		},
	],
};
